/**
 * 匿名掲示板API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorProperties'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ErrorProperties'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.Errors = factory(root.Api.ApiClient, root.Api.ErrorProperties);
  }
}(this, function(ApiClient, ErrorProperties) {
  'use strict';



  /**
   * The Errors model module.
   * @module model/Errors
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Errors</code>.
   * @alias module:model/Errors
   * @class
   * @param errors {Array.<module:model/ErrorProperties>} 
   */
  var exports = function(errors) {
    var _this = this;

    _this['errors'] = errors;
  };

  /**
   * Constructs a <code>Errors</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Errors} obj Optional instance to populate.
   * @return {module:model/Errors} The populated <code>Errors</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('errors')) {
        obj['errors'] = ApiClient.convertToType(data['errors'], [ErrorProperties]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ErrorProperties>} errors
   */
  exports.prototype['errors'] = undefined;



  return exports;
}));


