/*
 * userapi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetUsers -
func GetUsers(c *gin.Context) {
	// OpenAPIから生成されたUsers構造体を利用(model_users.go内に定義)
	u := Users{
		Users: []UserProperties{
			{
				Id:   1,
				Name: "po3rin",
			},
			{
				Id:   2,
				Name: "po4rin",
			},
		},
	}

	// レスポンスを返す
	c.JSON(http.StatusOK, u)
}
