go111:
	docker run -it --rm -v ${PWD}:/go/src/performance go111 ${CMD}

go112:
	docker run -it --rm -v ${PWD}:/go/src/performance go112 ${CMD}

build111:
	docker build -t go111 --target go111 .

build112:
	docker build -t go112 --target go112 .
