/**
 * 匿名掲示板API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PostProperties'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PostProperties'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.Post = factory(root.Api.ApiClient, root.Api.PostProperties);
  }
}(this, function(ApiClient, PostProperties) {
  'use strict';



  /**
   * The Post model module.
   * @module model/Post
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Post</code>.
   * @alias module:model/Post
   * @class
   * @param post {module:model/PostProperties} 
   */
  var exports = function(post) {
    var _this = this;

    _this['post'] = post;
  };

  /**
   * Constructs a <code>Post</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Post} obj Optional instance to populate.
   * @return {module:model/Post} The populated <code>Post</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('post')) {
        obj['post'] = PostProperties.constructFromObject(data['post']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PostProperties} post
   */
  exports.prototype['post'] = undefined;



  return exports;
}));


